### ISSUE TITLE
PacketFIFO: Dummy `param_layout` causes Migen error

### ISSUE THREAD

**Issue by ajelinski** [enjoy-digital/litex#1018]
The problem appears in LiteICLink's `test_serwb`.

This seems to be a problematic commit in LiteX: https://github.com/enjoy-digital/litex/commit/0a919e709f08b2825e86853529dea504629d4965.
The test is successful using its parent commit: https://github.com/enjoy-digital/litex/commit/b2f8fa5464840f51ba7d8fc783ef0fffb1463b50.

```
$ python3 -m unittest -v
test_scrambler (test.test_serwb_core.TestSERWBCore) ... ok
test_serwb (test.test_serwb_core.TestSERWBCore) ... ERROR
test_master_init_failure (test.test_serwb_init.TestSERWBInit) ... ok
test_master_init_success (test.test_serwb_init.TestSERWBInit) ... ok
test_slave_init_failure (test.test_serwb_init.TestSERWBInit) ... ok
test_slave_init_success (test.test_serwb_init.TestSERWBInit) ... ok

======================================================================
ERROR: test_serwb (test.test_serwb_core.TestSERWBCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<...>/liteiclink/test/test_serwb_core.py", line 172, in test_serwb
    dut = DUTCore()
  File "<...>/liteiclink/test/test_serwb_core.py", line 91, in __init__ 
    serwb_slave = SERWBCore(phy_slave, int(1e6), "slave")
  File "<...>/liteiclink/liteiclink/serwb/core.py", line 22, in __init__ 
    self.submodules.etherbone = etherbone = Etherbone(mode, etherbone_buffer_depth)
  File "<...>/liteiclink/liteiclink/serwb/etherbone.py", line 543, in __init__
    self.submodules.record = record = _EtherboneRecord(buffer_depth)
  File "<...>/liteiclink/liteiclink/serwb/etherbone.py", line 391, in __init__
    self.submodules.sender = sender = _EtherboneRecordSender(buffer_depth)
  File "<...>/liteiclink/liteiclink/serwb/etherbone.py", line 332, in __init__
    fifo = PacketFIFO(etherbone_mmap_description(32), buffer_depth, buffered=True)
  File "<...>/litex/litex/soc/interconnect/packet.py", line 414, in __init__
    param_fifo.source.connect(source,   omit={"last",  "ready"}),
  File "<...>/migen/migen/genlib/record.py", line 165, in connect 
    r += self_e.connect(getattr(slave, field), keep=keep, omit=omit)
  File "<...>/migen/migen/genlib/record.py", line 158, in connect 
    r += [getattr(slave, field).eq(self_e) for slave in slaves]
  File "<...>/migen/migen/genlib/record.py", line 158, in <listcomp>
    r += [getattr(slave, field).eq(self_e) for slave in slaves]

AttributeError: 'Record' object has no attribute 'dummy'
```

**Comment by enjoy-digital** [comment]
Thanks for the feedback @ajelinski, this is fixed with https://github.com/enjoy-digital/litex/commit/fa5fd765a4fdc1c4c820e2af6180626c763db076.
