### ISSUE TITLE
ModuleNotFoundError: No module named 'litex_boards'

### ISSUE THREAD

**Issue by athurwo** [enjoy-digital/litex#1660]
hello,

when I cd litex-boards/litex_boards/targets/, and python digilent_genesys2.py,

then info error below:

Traceback (most recent call last):
  File "/home/fso/LiteX/litex-boards/litex_boards/targets/digilent_genesys2.py", line 13, in <module>
    from litex_boards.platforms import digilent_genesys2
ModuleNotFoundError: No module named 'litex_boards'

why? I had in litex-boards folder. 

Please help me resovle it, thanks.

**Comment by enjoy-digital** [comment]
Hi @athurwo,

in litex_boards directory, can you do a `python3 setup.py develop?`

**Comment by athurwo** [comment]
> Hi @athurwo,
> 
> in litex_boards directory, can you do a `python3 setup.py develop?`

hello,

thanks,  now I do 'python3 setup.py develop'  in litex_boards directory,
and do 'python digilent_genesys2.py' again, another error below:

Traceback (most recent call last):
  File "/home/fso/LiteX/litex-boards/litex_boards/targets/digilent_genesys2.py", line 20, in <module>
    from litedram.modules import MT41J256M16
ModuleNotFoundError: No module named 'litedram'

**Comment by enjoy-digital** [comment]
@athurwo: It seems the LiteX repos are not correctly installed. To fix this issue, you'll have to the same in LiteDRAM. But it could be preferable to (re)doa `: sudo ./litex_setup.py --install`

**Comment by athurwo** [comment]
@enjoy-digital thanks,  I try to reinstall.

**Comment by athurwo** [comment]
hello @enjoy-digital
I redo flow, now the error from litex_sim --cpu-type=vexriscv

Traceback (most recent call last):
  File "/home/fso/.local/bin/litex_sim", line 33, in <module>
    sys.exit(load_entry_point('litex', 'console_scripts', 'litex_sim')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fso/LiteX/litex/litex/tools/litex_sim.py", line 547, in main
    builder.build(
  File "/home/fso/LiteX/litex/litex/soc/integration/builder.py", line 367, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fso/LiteX/litex/litex/soc/integration/soc.py", line 1310, in build
    return self.platform.build(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fso/LiteX/litex/litex/build/sim/platform.py", line 57, in build
    return self.toolchain.build(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fso/LiteX/litex/litex/build/sim/verilator.py", line 272, in build
    _compile_sim(build_name, verbose)
  File "/home/fso/LiteX/litex/litex/build/sim/verilator.py", line 169, in _compile_sim
    raise OSError("Subprocess failed with {}\n{}".format(p.returncode, "\n".join(error_messages)))
OSError: Subprocess failed with 2
make: Entering directory '/home/fso/LiteX/litex-boards/litex_boards/targets/build/sim/gateware'
mkdir -p modules
make -C modules -f /home/fso/LiteX/litex/litex/build/sim/core/modules/Makefile
make[1]: Entering directory '/home/fso/LiteX/litex-boards/litex_boards/targets/build/sim/gateware/modules'
mkdir -p xgmii_ethernet
make MOD=xgmii_ethernet -C xgmii_ethernet -f /home/fso/LiteX/litex/litex/build/sim/core/modules/xgmii_ethernet/Makefile
make[2]: Entering directory '/home/fso/LiteX/litex-boards/litex_boards/targets/build/sim/gateware/modules/xgmii_ethernet'
cc -c -Wall -O3 -ggdb -fPIC -Werror -I/home/fso/LiteX/pythondata-misc-tapcfg/pythondata_misc_tapcfg/data/src/include -I/home/fso/LiteX/litex/litex/build/sim/core/modules/xgmii_ethernet/../.. -o xgmii_ethernet.o /home/fso/LiteX/litex/litex/build/sim/core/modules/xgmii_ethernet/xgmii_ethernet.c
/home/fso/LiteX/litex/litex/build/sim/core/modules/xgmii_ethernet/xgmii_ethernet.c:8:10: fatal error: event2/listener.h: No such file or directory
    8 | #include <event2/listener.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/fso/LiteX/litex/litex/build/sim/core/modules/rules.mak:26: xgmii_ethernet.o] Error 1
make[2]: Leaving directory '/home/fso/LiteX/litex-boards/litex_boards/targets/build/sim/gateware/modules/xgmii_ethernet'
make[1]: *** [/home/fso/LiteX/litex/litex/build/sim/core/modules/Makefile:9: xgmii_ethernet] Error 2
make[1]: Leaving directory '/home/fso/LiteX/litex-boards/litex_boards/targets/build/sim/gateware/modules'
make: *** [/home/fso/LiteX/litex/litex/build/sim/core/Makefile:69: modules] Error 2
make: Leaving directory '/home/fso/LiteX/litex-boards/litex_boards/targets/build/sim/gateware'

**Comment by enjoy-digital** [comment]
Hi,

please make sure to follow https://github.com/enjoy-digital/litex#quick-start-guide, step 5 for your issue.

**Comment by enjoy-digital** [comment]
This looks like an installation/environment issue and should be covered by the current quick start guide:

  https://github.com/enjoy-digital/litex#quick-start-guide

The initial `No module named 'litex_boards'` / `No module named 'litedram'` errors mean the LiteX repositories were not installed in the active Python environment. The recommended way is to install/ update the LiteX ecosystem with `litex_setup.py`.

The later `event2/listener.h: No such file or directory` error is a missing host dependency for `litex_sim`. On Ubuntu/Debian, the required packages are:

sudo apt install libevent-dev libjson-c-dev verilator

Then retry:

litex_sim --cpu-type=vexriscv

Since the issue seems to be answered by the installation steps and there was no follow-up, I think we can close this.
