### ISSUE TITLE
Command `litex_term` on `terasic_de0nano` board is not working

### ISSUE THREAD

**Issue by FelipeWcosta** [enjoy-digital/litex#1663]
Hi everyone! I am relatively new using `litex`. In my first steps I just run the command line:
```
./terasic_de0nano.py --uart-name=jtag_uart --build --load
```
and then the process was completed very well, in the end I could see the LED's pattern flashing. When I try to run:
```
litex_term --jtag-config ../prog/openocd_max10_blaster.cfg jtag
```
This error appears to me:
```
Open On-Chip Debugger 0.11.0-R22.2
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
../prog/openocd_max10_blaster.cfg:1: Error: Can't find interface/altera-usb-blaster.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 26
at file "../prog/openocd_max10_blaster.cfg", line 1
Exception in thread Thread-1 (jtag2tcp):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fcost/python-litex/litex/litex/tools/litex_term.py", line 167, in jtag2tcp
    prog.stream(self.port, self.chain)
  File "/home/fcost/python-litex/litex/litex/build/openocd.py", line 190, in stream
    self.call(["openocd", "-f", config, "-f", "stream.cfg", "-c", script])
  File "/home/fcost/python-litex/litex/litex/build/generic_programmer.py", line 101, in call
    raise OSError(msg)
OSError: Error occured during OpenOCD's call, please check:
- OpenOCD installation.
- Access permissions.
- Hardware and cable.
- Bitstream presence.
Exception in thread Thread-3 (tcp2pty):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fcost/python-litex/litex/litex/tools/litex_term.py", line 176, in tcp2pty
    r = self.tcp.recv(1)
OSError: [Errno 107] Transport endpoint is not connected
Exception in thread Thread-2 (pty2tcp):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fcost/python-litex/litex/litex/tools/litex_term.py", line 172, in pty2tcp
    self.tcp.send(r)
BrokenPipeError: [Errno 32] Broken pipe
```
Thanks guys!

**Comment by FelipeWcosta** [comment]
When I changed the permissions of the files in `litex-boards/litex_boards/prog` with `chmod +x <file>` the same error was persisted.

**Comment by FelipeWcosta** [comment]
Greetings!

I've had some progress in this issue. In this case I've could access the `BIOS` just going to an upper directory with `cd ../` and also I've could set some LEDs like a test but after some time the erro showing below appears to me:
```
Error: ftdi_write_data: usb bulk write failed
```

**Comment by FelipeWcosta** [comment]
I followed the installation of OpenOCD available on `linux-litex-on-vexriscv` repo and the older erro disappeared but I get this other erro:
```
Error: No lowlevel driver available
```
Someone is faced this error yet? Or any tip for fix it?
