### ISSUE TITLE
litex_sim --cpu-type=vexriscv  failed with gcc ERROR [EDIT: wrong title]

### ISSUE THREAD

**Issue by OJthe123** [enjoy-digital/litex#1680]
> make: Verzeichnis „/home/oj/fpga/build/sim/software/libc“ wird betreten
> if [ -d "/home/oj/fpga/litex/litex/soc/software/libc/riscv" ]; then \
> 	cp /home/oj/fpga/litex/litex/soc/software/libc/riscv/* /home/oj/fpga/pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/machine/riscv/ ;\
> fi
> meson /home/oj/fpga/pythondata-software-picolibc/pythondata_software_picolibc/data \
> 	-Dmultilib=false \
> 	-Dpicocrt=false \
> 	-Datomic-ungetc=false \
> 	-Dthread-local-storage=false \
> 	-Dio-long-long=true \
> 	-Dformat-default=integer \
> 	-Dincludedir=picolibc/riscv64-linux-gnu/include \
> 	-Dlibdir=picolibc/riscv64-linux-gnu/lib \
> 	--cross-file cross.txt
> WARNING: Unknown CPU family riscv, please report this at https://github.com/mesonbuild/meson/issues/new
> The Meson build system
> Version: 1.1.0
> Source dir: /home/oj/fpga/pythondata-software-picolibc/pythondata_software_picolibc/data
> Build dir: /home/oj/fpga/build/sim/software/libc
> Build type: cross build
> Project name: picolibc
> Project version: 1.7.9
> 
> ../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/meson.build:35:0: ERROR: Compiler riscv64-linux-gnu-gcc can not compile programs.
> 
> A full log can be found at /home/oj/fpga/build/sim/software/libc/meson-logs/meson-log.txt
> WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
> make: *** [/home/oj/fpga/litex/litex/soc/software/libc/Makefile:43: __libc.a] Fehler 1
> make: Verzeichnis „/home/oj/fpga/build/sim/software/libc“ wird verlassen
> Traceback (most recent call last):
>   File "/home/oj/.local/bin/litex_sim", line 11, in <module>
>     load_entry_point('litex', 'console_scripts', 'litex_sim')()
>   File "/home/oj/fpga/litex/litex/tools/litex_sim.py", line 552, in main
>     **parser.toolchain_argdict,
>   File "/home/oj/fpga/litex/litex/soc/integration/builder.py", line 354, in build
>     self._generate_rom_software(compile_bios=use_bios)
>   File "/home/oj/fpga/litex/litex/soc/integration/builder.py", line 288, in _generate_rom_software
>     subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
>   File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['make', '-C', '/home/oj/fpga/build/sim/software/libc', '-f', '/home/oj/fpga/litex/
> litex/soc/software/libc/Makefile']' returned non-zero exit status 2.

I did a fresh install in my virtual machine and followed the WIKI Installation instructions
What does that error mean?
ERROR: Compiler riscv64-linux-gnu-gcc can not compile programs.

**Comment by OJthe123** [comment]
Linux Debian 4.19.0-21-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.249-2 x86_64 GNU/Linux

**Comment by OJthe123** [comment]
I installed Ubuntu 22 ISO and now it works.....
