### ISSUE TITLE
Xilinx zcu102 build failure

### ISSUE THREAD

**Issue by lianakoleva** [enjoy-digital/litex#1788]
Upon running command `litex-boards/litex_boards/targets/xilinx_zcu102.py --build`, I experience a failure during the placement step:

`# place_design -directive default`
`Command: place_design -directive default`
`Attempting to get a license for feature 'Implementation' and/or device 'xczu9eg'`
`INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xczu9eg'`
`INFO: [DRC 23-27] Running DRC with 4 threads`
`INFO: [Vivado_Tcl 4-198] DRC finished with 0 Errors`
`INFO: [Vivado_Tcl 4-199] Please refer to the DRC report (report_drc) for more information.`
`Running DRC as a precondition to command place_design`
`INFO: [DRC 23-27] Running DRC with 4 threads`
`ERROR: [DRC BIVB-1] Bank IO standard Support: Bank 47 has incompatible IO(s) because: The LVDS I/O standard is not supported for banks of type High Density.  Move the following ports or change their properties:  `
`clk125_p`
`INFO: [Vivado_Tcl 4-198] DRC finished with 1 Errors`
`ERROR: [Vivado_Tcl 4-23] Error(s) found during DRC. Placer not run.`
`INFO: [Vivado_Tcl 4-199] Please refer to the DRC report (report_drc) for more information.`
`INFO: [Common 17-83] Releasing license: Implementation`
`8 Infos, 0 Warnings, 0 Critical Warnings and 2 Errors encountered.`
`place_design failed`
`place_design: Time (s): cpu = 00:00:10 ; elapsed = 00:00:05 . Memory (MB): peak = 4947.023 ; gain = 0.000 ; free physical = 3857 ; free virtual = 8858`
`ERROR: [Common 17-39] 'place_design' failed due to earlier errors.`

`    while executing`
`"place_design -directive default"`
`    (file "xilinx_zcu102.tcl" line 49)`
`INFO: [Common 17-206] Exiting Vivado at Fri Sep 22 16:58:49 2023...`
`Traceback (most recent call last):`
`  File "/home/liana/git/litex_main/litex-boards/litex_boards/targets/xilinx_zcu102.py", line 59, in <module>`
`    main()`
`  File "/home/liana/git/litex_main/litex-boards/litex_boards/targets/xilinx_zcu102.py", line 52, in main`
`    builder.build(**parser.toolchain_argdict)`
`  File "/home/liana/git/litex_main/litex/litex/soc/integration/builder.py", line 367, in build`
`    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)`
`  File "/home/liana/git/litex_main/litex/litex/soc/integration/soc.py", line 1332, in build`
`    return self.platform.build(self, *args, **kwargs)`
`  File "/home/liana/git/litex_main/litex/litex/build/xilinx/platform.py", line 85, in build`
`    return self.toolchain.build(self, *args, **kwargs)`
`  File "/home/liana/git/litex_main/litex/litex/build/xilinx/vivado.py", line 140, in build`
`    return GenericToolchain.build(self, platform, fragment, **kwargs)`
`  File "/home/liana/git/litex_main/litex/litex/build/generic_toolchain.py", line 123, in build`
`    self.run_script(script)`
`  File "/home/liana/git/litex_main/litex/litex/build/xilinx/vivado.py", line 396, in run_script`
`    raise OSError("Error occured during Vivado's script execution.")`
`OSError: Error occured during Vivado's script execution.`

I have attached the whole console output: [out.txt](https://github.com/enjoy-digital/litex/files/12712511/out.txt).

**Comment by lianakoleva** [comment]
Resolved by changing IOStandard from "LVDS" to "LVDS_25" in litex-boards/litex_boards/platforms/xilinx_zcu102.py. Submitted [PR ](https://github.com/litex-hub/litex-boards/pull/532) to litex-boards repo.
