### ISSUE TITLE
Python minimum requirement should be updated.

### ISSUE THREAD

**Issue by hardiselg** [enjoy-digital/litex#1847]
Hi,

As a suggestion, the python's requirement should be updated to Python v3.7+
I tried to run `litex_sim` with following arguments:

`litex_sim --with-sdram --no-compile-gateware -cpu-type=cv32e40p --integrated-sram-size=32768 --cpu-variant=full --sim-debug --output-dir=/tmp/riscv/build`

and it gave me `SyntaxError: more than 255 arguments`
Python  3.7+ allows more than 255 arguments. [link](https://docs.python.org/3.7/whatsnew/3.7.html)

```shell
/bin/bash > litex_sim --with-sdram --no-compile-gateware -cpu-type=cv32e40p --integrated-sram-size=32768 --cpu-variant=full --sim-debug --output-dir=/tmp/hartz/riscv/build
Traceback (most recent call last):
  File "/home/hartz/.local/bin/litex_sim", line 11, in <module>
    load_entry_point('litex', 'console_scripts', 'litex_sim')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/scratch/hartz/riscv/litex/litex/tools/litex_sim.py", line 34, in <module>
    from liteeth.phy.gmii import LiteEthPHYGMII
  File "/scratch/hartz/riscv/liteeth/liteeth/phy/__init__.py", line 39, in <module>
    from liteeth.phy.usp_gth_1000basex import USP_GTH_1000BASEX
  File "/scratch/hartz/riscv/liteeth/liteeth/phy/usp_gth_1000basex.py", line 229
    p_RXBUFRESET_TIME              = 0b00011,
    ^
SyntaxError: more than 255 arguments
```

**Comment by enjoy-digital** [comment]
Thanks @hardiselg, this is done with https://github.com/enjoy-digital/litex/commit/048c42820c8b934d5dc60660eab075de009d8d4d and the similar commit in the other repositories.
