### ISSUE TITLE
Make Error *** No rule to make target 'boot-helper.o', needed by 'bios.elf'.  Stop. Neorv32 core TUL PYNQ Z2 

### ISSUE THREAD

**Issue by ZeroX29a** [enjoy-digital/litex#1861]
Executed command ```./tul_pynq_z2.py --cpu-type=neorv32 --cpu-variant full --build ```

Error 
this part stood out to me ``` make: *** No rule to make target 'boot-helper.o', needed by 'bios.elf'.  Stop.```
Any Help is much appreciated.

```
make: Leaving directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/liblitedram'
make: Entering directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/libliteeth'
 CC       udp.o
 CC       mdio.o
 AR       libliteeth.a
make: Leaving directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/libliteeth'
make: Entering directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/liblitesdcard'
 CC       sdcard.o
 CC       spisdcard.o
 AR       liblitesdcard.a
make: Leaving directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/liblitesdcard'
make: Entering directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/liblitesata'
 CC       sata.o
 AR       liblitesata.a
make: Leaving directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/liblitesata'
make: Entering directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/bios'
make: *** No rule to make target 'boot-helper.o', needed by 'bios.elf'.  Stop.
make: Leaving directory '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/bios'
Traceback (most recent call last):
  File "./tul_pynq_z2.py", line 88, in <module>
    main()
  File "./tul_pynq_z2.py", line 81, in main
    builder.build(**parser.toolchain_argdict)
  File "/home/litex/litex_installation/litex/litex/soc/integration/builder.py", line 357, in build
    self._generate_rom_software(compile_bios=use_bios)
  File "/home/litex/litex_installation/litex/litex/soc/integration/builder.py", line 291, in _generate_rom_software
    subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/home/litex/litex_installation/litex-boards/litex_boards/targets/build/tul_pynq_z2/software/bios', '-f', '/home/litex/litex_installation/litex/litex/soc/software/bios/Makefile']' returned non-zero exit status 2.
```

**Comment by ZeroX29a** [comment]
After Scouring through the file dir and comparing other soc folders and the github files , i found that installer didnt install the helper from the repo, redownloaded the file and place it there, it compiled
