### ISSUE TITLE
Where did FrequencyMeter go?

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litex#295]
```
Traceback (most recent call last):
  File "./make.py", line 164, in <module>
    main()
  File "./make.py", line 123, in main
    soc = get_soc(args, platform)
  File "./make.py", line 56, in get_soc
    exec("from targets.{}.{} import SoC".format(args.platform, args.target.lower(), args.target), globals())
  File "<string>", line 1, in <module>
  File "/usr/local/google/home/tansell/github/timvideos/litex-buildenv-clean/targets/nexys_video/video.py", line 4, in <module>
    from litex.soc.cores.frequency_meter import FrequencyMeter
ModuleNotFoundError: No module named 'litex.soc.cores.frequency_meter'
```

**Comment by enjoy-digital** [comment]
It's just renamed: https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/freqmeter.py#L38
