### ISSUE TITLE
Regression: `Unsupported variant min`

### ISSUE THREAD

**Issue by xobs** [enjoy-digital/litex#384]
When using the latest litex, the following error is generated:

```
Traceback (most recent call last):
  File ".\foboot-bitstream.py", line 477, in <module>
    main()
  File ".\foboot-bitstream.py", line 443, in main
    warmboot_offsets=warmboot_offsets[1:])
  File ".\foboot-bitstream.py", line 140, in __init__
    SoCCore.__init__(self, platform, clk_freq, integrated_sram_size=0, with_uart=False, csr_data_width=32, **kwargs)
  File "D:\Code\Fomu\foboot\hw\deps\litex\litex\soc\integration\soc_core.py", line 154, in __init__
    reset_address = None if integrated_rom_size else cpu_reset_address)
  File "D:\Code\Fomu\foboot\hw\deps\litex\litex\soc\integration\soc.py", line 762, in add_cpu
    self.submodules.cpu = cpu.CPUS[name](self.platform, variant)
  File "D:\Code\Fomu\foboot\hw\deps\litex\litex\soc\cores\cpu\vexriscv\core.py", line 102, in __init__
    assert variant in CPU_VARIANTS, "Unsupported variant %s" % variant
AssertionError: Unsupported variant min
```

**Comment by enjoy-digital** [comment]
Thanks for reporting, that's fixed with https://github.com/enjoy-digital/litex/commit/e4712ff7f32020716a802ded776bea18aa53a092.
