### ISSUE TITLE
litex_server seems to be broken

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litex#6]
https://travis-ci.org/mithro/litex
```
The command "litex_server --help" exited with 0.
0.16s$ litex_client --help || true
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: 'module' object has no attribute 'main'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.5/bin/litex_client", line 9, in <module>
    load_entry_point('litex==0.1+37.g512098f', 'console_scripts', 'litex_client')()
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/pkg_resources/__init__.py", line 2320, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
```

**Comment by enjoy-digital** [comment]
Closed via https://github.com/enjoy-digital/litex/commit/8efd57f766e7a9475d735973ef6a2e9c8a51d0e1.
