### ISSUE TITLE
Region overlap between ethmac and csr (arty + microwatt)

### ISSUE THREAD

**Issue by shenki** [enjoy-digital/litex#826]
```
$ ./litex_boards/targets/arty.py --cpu-type microwatt --cpu-variant standard+irq --integrated-rom-size=$((48 * 1024)) --build --variant a7-100 --with-ethernet
INFO:SoC:        __   _ __      _  __  
INFO:SoC:       / /  (_) /____ | |/_/  
INFO:SoC:      / /__/ / __/ -_)>  <    
INFO:SoC:     /____/_/\__/\__/_/|_|  
INFO:SoC:  Build your hardware, easily!
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Creating SoC... (2021-02-24 09:43:43)
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:FPGA device : xc7a100tcsg324-1.
INFO:SoC:System clock: 100.00MHz.
INFO:SoCBusHandler:Creating Bus Handler...
INFO:SoCBusHandler:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoCBusHandler:Adding reserved Bus Regions...
INFO:SoCBusHandler:Bus Handler created.
INFO:SoCCSRHandler:Creating CSR Handler...
INFO:SoCCSRHandler:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoCCSRHandler:Adding reserved CSRs...
INFO:SoCCSRHandler:CSR Handler created.
INFO:SoCIRQHandler:Creating IRQ Handler...
INFO:SoCIRQHandler:IRQ Handler (up to 32 Locations).
INFO:SoCIRQHandler:Adding reserved IRQs...
INFO:SoCIRQHandler:IRQ Handler created.
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Initial SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoC:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoC:IRQ Handler (up to 32 Locations).
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCCSRHandler:ctrl CSR allocated at Location 0.
INFO:SoCBusHandler:io0 Region added at Origin: 0xc0000000, Size: 0x10000000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:cpu_bus0 Bus converted from Wishbone 64-bit to Wishbone 32-bit.
INFO:SoCBusHandler:cpu_bus0 added as Bus Master.
INFO:SoCBusHandler:cpu_bus1 Bus converted from Wishbone 64-bit to Wishbone 32-bit.
INFO:SoCBusHandler:cpu_bus1 added as Bus Master.
INFO:SoCCSRHandler:cpu CSR allocated at Location 1.
INFO:SoCBusHandler:xicsicp Region added at Origin: 0xc3ff0000, Size: 0x00001000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:xicsicp added as Bus Slave.
INFO:SoCBusHandler:xicsics Region added at Origin: 0xc3ff1000, Size: 0x00001000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:xicsics added as Bus Slave.
INFO:SoCRegion:Region size rounded internally from 0x0000c000 to 0x00010000.
INFO:SoCBusHandler:rom Region added at Origin: 0x00000000, Size: 0x0000c000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:rom added as Bus Slave.
INFO:SoC:RAM rom added Origin: 0x00000000, Size: 0x0000c000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:sram Region added at Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:sram added as Bus Slave.
INFO:SoC:RAM sram added Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCCSRHandler:identifier_mem CSR allocated at Location 2.
INFO:SoCCSRHandler:uart_phy CSR allocated at Location 3.
INFO:SoCCSRHandler:uart CSR allocated at Location 4.
INFO:SoCIRQHandler:uart IRQ allocated at Location 0.
INFO:SoCCSRHandler:timer0 CSR allocated at Location 5.
INFO:SoCIRQHandler:timer0 IRQ allocated at Location 1.
INFO:S7PLL:Creating S7PLL, speedgrade -1.
INFO:S7PLL:Registering Single Ended ClkIn of 100.00MHz.
INFO:S7PLL:Creating ClkOut0 sys of 100.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut1 sys4x of 400.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut2 sys4x_dqs of 400.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut3 idelay of 200.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut4 eth of 25.00MHz (+-10000.00ppm).
INFO:SoCCSRHandler:ddrphy CSR allocated at Location 6.
INFO:SoCCSRHandler:sdram CSR allocated at Location 7.
INFO:SoCBusHandler:main_ram Region added at Origin: 0x40000000, Size: 0x10000000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:main_ram added as Bus Slave.
INFO:SoCCSRHandler:ethphy CSR allocated at Location 8.
INFO:SoCBusHandler:Allocating IO Region of size 0x00002000...
INFO:SoCBusHandler:ethmac Region allocated at Origin: 0xc0000000, Size: 0x00002000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:ethmac added as Bus Slave.
INFO:SoCCSRHandler:ethmac CSR allocated at Location 9.
INFO:SoCIRQHandler:ethmac IRQ allocated at Location 2.
INFO:SoCBusHandler:jtagbone added as Bus Master.
INFO:SoCCSRHandler:leds CSR allocated at Location 10.
INFO:S7PLL:Config:
divclk_divide : 1
clkout0_freq  : 100.00MHz
clkout0_divide: 16
clkout0_phase : 0.00°
clkout1_freq  : 400.00MHz
clkout1_divide: 4
clkout1_phase : 0.00°
clkout2_freq  : 400.00MHz
clkout2_divide: 4
clkout2_phase : 90.00°
clkout3_freq  : 200.00MHz
clkout3_divide: 8
clkout3_phase : 0.00°
clkout4_freq  : 25.00MHz
clkout4_divide: 64
clkout4_phase : 0.00°
vco           : 1600.00MHz
clkfbout_mult : 16
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Finalized SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
IO Regions: (1)
io0                 : Origin: 0xc0000000, Size: 0x10000000, Mode: RW, Cached: False Linker: False
Bus Regions: (6)
rom                 : Origin: 0x00000000, Size: 0x0000c000, Mode: R, Cached: True Linker: False
sram                : Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False
main_ram            : Origin: 0x40000000, Size: 0x10000000, Mode: RW, Cached: True Linker: False
ethmac              : Origin: 0xc0000000, Size: 0x00002000, Mode: RW, Cached: False Linker: False
xicsicp             : Origin: 0xc3ff0000, Size: 0x00001000, Mode: RW, Cached: False Linker: False
xicsics             : Origin: 0xc3ff1000, Size: 0x00001000, Mode: RW, Cached: False Linker: False
Bus Masters: (3)
- cpu_bus0
- cpu_bus1
- jtagbone
Bus Slaves: (6)
- xicsicp
- xicsics
- rom
- sram
- main_ram
- ethmac
INFO:SoC:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
CSR Locations: (11)
- ctrl           : 0
- cpu            : 1
- identifier_mem : 2
- uart_phy       : 3
- uart           : 4
- timer0         : 5
- ddrphy         : 6
- sdram          : 7
- ethphy         : 8
- ethmac         : 9
- leds           : 10
INFO:SoC:IRQ Handler (up to 32 Locations).
IRQ Locations: (3)
- uart   : 0
- timer0 : 1
- ethmac : 2
INFO:SoC:--------------------------------------------------------------------------------
ERROR:SoCBusHandler:Region overlap between ethmac and csr:
ERROR:SoCBusHandler:Origin: 0xc0000000, Size: 0x00002000, Mode: RW, Cached: False Linker: False
ERROR:SoCBusHandler:Origin: 0xc0000000, Size: 0x00010000, Mode: RW, Cached: False Linker: False
Traceback (most recent call last):
  File "/home/joel/dev/litex/litex-boards/./litex_boards/targets/arty.py", line 158, in <module>
    main()
  File "/home/joel/dev/litex/litex-boards/./litex_boards/targets/arty.py", line 151, in main
    builder.build(**builder_kwargs, run=args.build)
  File "/home/joel/dev/litex/litex/litex/soc/integration/builder.py", line 202, in build
    self.soc.finalize()
  File "/home/joel/dev/litex/migen/migen/fhdl/module.py", line 157, in finalize
    self.do_finalize(*args, **kwargs)
  File "/home/joel/dev/litex/litex/litex/soc/integration/soc_core.py", line 244, in do_finalize
    SoC.do_finalize(self)
  File "/home/joel/dev/litex/litex/litex/soc/integration/soc.py", line 947, in do_finalize
    self.add_csr_bridge(self.mem_map["csr"], register=hasattr(self, "sdram"))
  File "/home/joel/dev/litex/litex/litex/soc/integration/soc.py", line 837, in add_csr_bridge
    self.bus.add_slave("csr", bus, csr_region)
  File "/home/joel/dev/litex/litex/litex/soc/integration/soc.py", line 376, in add_slave
    self.add_region(name, region)
  File "/home/joel/dev/litex/litex/litex/soc/integration/soc.py", line 213, in add_region
    raise
RuntimeError: No active exception to reraise
```

I did some investigation but cannot work out why litex is trying to place the ethmac buffers in the same place as the csr region.

**Comment by enjoy-digital** [comment]
Hi @shenki,

thanks for the feedback and sorry for the delay. The way we are defining the specific memory map of the CPU for now does not allow us to pass the size we then have some limitations like the one you hit. For now, I moved the mem_map of the CPU by 128MBs to allow the SoC to use these 128MBs for IO allocation with https://github.com/enjoy-digital/litex/commit/4c26dbe98f826da1732dc0bd99a48e3f7cfd43c4.

I've been able to test it successfully on an Arty-35T with: 
`./digilent_arty.py --cpu-type microwatt --cpu-variant standard+irq --with-ethernet --build --load`
