### ISSUE TITLE
Litex_sim not working on GitHub Actions

### ISSUE THREAD

**Issue by developandplay** [enjoy-digital/litex#882]
**Describe the bug**
When running litex_sim in CI environments like GitHub Actions it will fail due to missing stdin.

**To Reproduce**
Execture litex_sim on GitHub Actions or have a look at this [log](https://github.com/scanakci/linux-on-litex-blackparrot/runs/2338772911).

**Expected behavior**
When running on a non interactive environment we should have an option to disable stdin.

**Log output**
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/litex_sim", line 11, in <module>
    load_entry_point('litex', 'console_scripts', 'litex_sim')()
  File "/home/runner/work/linux-on-litex-blackparrot/linux-on-litex-blackparrot/litex/litex/tools/litex_sim.py", line 374, in main
    builder.build(build=False, threads=args.threads, sim_config=sim_config,
  File "/home/runner/work/linux-on-litex-blackparrot/linux-on-litex-blackparrot/litex/litex/soc/integration/builder.py", line 214, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/runner/work/linux-on-litex-blackparrot/linux-on-litex-blackparrot/litex/litex/soc/integration/soc.py", line 911, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/runner/work/linux-on-litex-blackparrot/linux-on-litex-blackparrot/litex/litex/build/sim/platform.py", line 44, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/runner/work/linux-on-litex-blackparrot/linux-on-litex-blackparrot/litex/litex/build/sim/verilator.py", line 216, in build
    _run_sim(build_name, as_root=run_as_root)
  File "/home/runner/work/linux-on-litex-blackparrot/linux-on-litex-blackparrot/litex/litex/build/sim/verilator.py", line 161, in _run_sim
    termios_settings = termios.tcgetattr(sys.stdin.fileno())
termios.error: (25, 'Inappropriate ioctl for device')
```

**Proposed Solution**
Add a `--non-interactive` flag or environmental variable to litex_sim which then propagates to:
https://github.com/enjoy-digital/litex/blob/246142256b29d707b9b20ed3c4f35df833e666dd/litex/build/sim/verilator.py#L158-L173
Similar to `win32` the `interactive` should be used to determine whether stdin should be enabled.
I created a [draft pull request](https://github.com/enjoy-digital/litex/pull/881) with the proposed `interactive` parameter for `_run_sim`. However I'm looking for your feedback on how this information should be passed to `_run_sim`.

**Environment:**
 - CI: GitHub Actions
 - OS: Ubuntu 20.04

**Additional context**
I'm trying to automate testing for the [linux-on-litex-blackparrot](https://github.com/scanakci/linux-on-litex-blackparrot) project.

**Comment by developandplay** [comment]
@enjoy-digital 
Thanks for accepting #881 !
With #948 we can now expose it to GitHub Actions users and close this issue.
