### ISSUE TITLE
Incorrect SpiFlash origin aligment

### ISSUE THREAD

**Issue by MateuszKosmala** [enjoy-digital/litex#959]
While building digilent_arty target with switches like:
`python3 digilent_arty.py --csr-csv csr.csv --with-ethernet --with-mapped-flash --eth-dynamic-ip --load --build`
I've got exception:
```
INFO:SoC:        __   _ __      _  __  
INFO:SoC:       / /  (_) /____ | |/_/  
INFO:SoC:      / /__/ / __/ -_)>  <    
INFO:SoC:     /____/_/\__/\__/_/|_|  
INFO:SoC:  Build your hardware, easily!
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Creating SoC... (2021-06-28 16:49:02)
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:FPGA device : xc7a35ticsg324-1L.
INFO:SoC:System clock: 100.00MHz.
INFO:SoCBusHandler:Creating Bus Handler...
INFO:SoCBusHandler:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoCBusHandler:Adding reserved Bus Regions...
INFO:SoCBusHandler:Bus Handler created.
INFO:SoCCSRHandler:Creating CSR Handler...
INFO:SoCCSRHandler:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoCCSRHandler:Adding reserved CSRs...
INFO:SoCCSRHandler:CSR Handler created.
INFO:SoCIRQHandler:Creating IRQ Handler...
INFO:SoCIRQHandler:IRQ Handler (up to 32 Locations).
INFO:SoCIRQHandler:Adding reserved IRQs...
INFO:SoCIRQHandler:IRQ Handler created.
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Initial SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoC:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoC:IRQ Handler (up to 32 Locations).
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCBusHandler:io0 Region added at Origin: 0x80000000, Size: 0x80000000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:cpu_bus0 added as Bus Master.
INFO:SoCBusHandler:cpu_bus1 added as Bus Master.
INFO:SoCBusHandler:rom Region added at Origin: 0x00000000, Size: 0x00020000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:rom added as Bus Slave.
INFO:SoC:RAM rom added Origin: 0x00000000, Size: 0x00020000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:sram Region added at Origin: 0x10000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:sram added as Bus Slave.
INFO:SoC:RAM sram added Origin: 0x10000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCIRQHandler:uart IRQ allocated at Location 0.
INFO:SoCIRQHandler:timer0 IRQ allocated at Location 1.
INFO:S7PLL:Creating S7PLL, speedgrade -1.
INFO:S7PLL:Registering Single Ended ClkIn of 100.00MHz.
INFO:S7PLL:Creating ClkOut0 sys of 100.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut1 sys4x of 400.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut2 sys4x_dqs of 400.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut3 idelay of 200.00MHz (+-10000.00ppm).
INFO:S7PLL:Creating ClkOut4 eth of 25.00MHz (+-10000.00ppm).
INFO:SoCBusHandler:main_ram Region added at Origin: 0x40000000, Size: 0x10000000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:main_ram added as Bus Slave.
INFO:SoCBusHandler:Allocating IO Region of size 0x00002000...
INFO:SoCBusHandler:ethmac Region allocated at Origin: 0x80000000, Size: 0x00002000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:ethmac added as Bus Slave.
INFO:SoCIRQHandler:ethmac IRQ allocated at Location 2.
INFO:SoCBusHandler:Allocating IO Region of size 0x01000000...
INFO:SoCBusHandler:spiflash Region allocated at Origin: 0x80002000, Size: 0x01000000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:spiflash added as Bus Slave.
INFO:S7PLL:Config:
divclk_divide : 1
clkout0_freq  : 100.00MHz
clkout0_divide: 16
clkout0_phase : 0.00°
clkout1_freq  : 400.00MHz
clkout1_divide: 4
clkout1_phase : 0.00°
clkout2_freq  : 400.00MHz
clkout2_divide: 4
clkout2_phase : 90.00°
clkout3_freq  : 200.00MHz
clkout3_divide: 8
clkout3_phase : 0.00°
clkout4_freq  : 25.00MHz
clkout4_divide: 64
clkout4_phase : 0.00°
vco           : 1600.00MHz
clkfbout_mult : 16
INFO:SoCBusHandler:csr Region added at Origin: 0xf0000000, Size: 0x00010000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:csr added as Bus Slave.
INFO:SoCCSRHandler:bridge added as CSR Master.
ERROR:SoCRegion:Origin needs to be aligned on size:
ERROR:SoCRegion:Origin: 0x80002000, Size: 0x01000000, Mode: RW, Cached: False Linker: False
Traceback (most recent call last):
  File "/home/m3et/Antmicro/litex-boards/litex_boards/targets/digilent_arty.py", line 172, in <module>
    main()
  File "/home/m3et/Antmicro/litex-boards/litex_boards/targets/digilent_arty.py", line 165, in main
    builder.build(**builder_kwargs, run=args.build)
  File "/home/m3et/Antmicro/litex/litex/soc/integration/builder.py", line 261, in build
    self.soc.finalize()
  File "/home/m3et/Antmicro/migen/migen/fhdl/module.py", line 157, in finalize
    self.do_finalize(*args, **kwargs)
  File "/home/m3et/Antmicro/litex/litex/soc/integration/soc_core.py", line 276, in do_finalize
    SoC.do_finalize(self)
  File "/home/m3et/Antmicro/litex/litex/soc/integration/soc.py", line 988, in do_finalize
    slaves         = [(self.bus.regions[n].decoder(self.bus), s) for n, s in self.bus.slaves.items()],
  File "/home/m3et/Antmicro/litex/litex/soc/integration/soc.py", line 988, in <listcomp>
    slaves         = [(self.bus.regions[n].decoder(self.bus), s) for n, s in self.bus.slaves.items()],
  File "/home/m3et/Antmicro/litex/litex/soc/integration/soc.py", line 75, in decoder
    raise
RuntimeError: No active exception to reraise
Skipping io region: ethmac
Skipping io region: csr
Skipping unsupported peripheral `analyzer` at 0xf0000000
Skipping unsupported peripheral `ethphy` at 0xf0002000
Skipping unsupported peripheral `identifier_mem` at 0xf0002800
Skipping unsupported peripheral `leds` at 0xf0003000
```
and it looks like Spiflash Origin address-**0x80002000** is incorrectly assigned because that check raises exception:
```
if (origin & (size - 1)) != 0:
            self.logger.error("Origin needs to be aligned on size:")
            self.logger.error(self)
            raise
```

I found two potential solutions to this problem:

- In target change Ethernet/Etherbone initialization after Flash(`if with_mapped_flash:` statement)

- Add additional memory assign check after: https://github.com/enjoy-digital/litex/blob/4d959bbc813952ccb41027fb259a114cc28cf232/litex/soc/integration/soc.py#L242 
```
if (origin & (size - 1)) != 0:
          origin  = allocated.origin + candidate.size_pow2
```

**Comment by enjoy-digital** [comment]
Thanks @MateuszKosmala for the feedback, this is fixed with https://github.com/enjoy-digital/litex/commit/88d302d4db4c61890654a0bd12e64b903c0410f3.
