### ISSUE TITLE
minerva.core package not found

### ISSUE THREAD

**Issue by bunnie** [enjoy-digital/litex#97]
I just fetched the latest commits and I get this error on trying to compile:

Traceback (most recent call last):
  File "/home/bunnie/code/netv2-merge/netv2mvp.py", line 25, in <module>
    from litex.soc.integration.soc_sdram import *
  File "/home/bunnie/code/netv2-merge/deps/litex/litex/soc/integration/__init__.py", line 1, in <module>
    from litex.soc.integration.soc_core import SoCCore
  File "/home/bunnie/code/netv2-merge/deps/litex/litex/soc/integration/soc_core.py", line 7, in <module>
    from litex.soc.cores.cpu import lm32, mor1kx, picorv32, vexriscv, minerva
  File "/home/bunnie/code/netv2-merge/deps/litex/litex/soc/cores/cpu/minerva/__init__.py", line 1, in <module>
    from litex.soc.cores.cpu.minerva.core import Minerva
  File "/home/bunnie/code/netv2-merge/deps/litex/litex/soc/cores/cpu/minerva/core.py", line 7, in <module>
    from litex.soc.cores.cpu.minerva.core import Minerva as MinervaCPU
ImportError: cannot import name 'Minerva'

Where do I grab the minerva package from?

**Comment by enjoy-digital** [comment]
Sorry, fixed via https://github.com/enjoy-digital/litex/commit/fb24ac0ecc158bd1f7b69649bfafc356a709e5a3.
